#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml 
  type-aliases-package: com.mengxuegu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product-config-dev			# ******服务名*******
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.153.130:3306/springcloud_db01?serverTimezone=GMT%2B8 #数据库连接地址，*****注意库名 db01***************
    username: root
    password: 'AQBxUQ3ZuSiSu0PyWp18h8u/BfuZ+/S2oMPM5eLl1TSusKQTYkd4KCzQ2z4PXFQqnZL7vBTiRDXfy687rrW6M0LDQhKpByuImHpgH9j3dOl6nsJX7PwxJsVwuvSsmvM2uN00r0l4pthohurGlrGftTlZ3FfEgJqtgdYd8ZoGK21LZFfWQwZcEEkemBi6W7pM1Rv1Y2csxaA27pOqA4JMC2aLOJroOO3UVPnrHPVXwJZRiD25Se8RzbR1IARioRwoDTaOwYxoIUlsYpew8iYCim7MXKvAt4VKh3CgyFBFBaNc0eSzpZ2j8NtzfZTtx0ulgcSQ7Yukuzmk0e0cUsWRMmeNdhDLk35NNds1eUXksxgyUyJ8raU6QcWc3+9TnCSYzak='
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
emp:
  name: zhangsan
  age: 10
  sex: 1
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml 
  type-aliases-package: com.mengxuegu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-product-config			# ******服务名*******
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.153.130:3306/springcloud_db02?serverTimezone=GMT%2B8 #数据库连接地址，*****注意库名 db02***************
    username: root
    password: 'AQBxUQ3ZuSiSu0PyWp18h8u/BfuZ+/S2oMPM5eLl1TSusKQTYkd4KCzQ2z4PXFQqnZL7vBTiRDXfy687rrW6M0LDQhKpByuImHpgH9j3dOl6nsJX7PwxJsVwuvSsmvM2uN00r0l4pthohurGlrGftTlZ3FfEgJqtgdYd8ZoGK21LZFfWQwZcEEkemBi6W7pM1Rv1Y2csxaA27pOqA4JMC2aLOJroOO3UVPnrHPVXwJZRiD25Se8RzbR1IARioRwoDTaOwYxoIUlsYpew8iYCim7MXKvAt4VKh3CgyFBFBaNc0eSzpZ2j8NtzfZTtx0ulgcSQ7Yukuzmk0e0cUsWRMmeNdhDLk35NNds1eUXksxgyUyJ8raU6QcWc3+9TnCSYzak='
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
